import { User } from "../../../types";

export const UserInitialState: User = {
   login: "MarkEdmondson1234",
   id: 3155884,
   node_id: "MDQ6VXNlcjMxNTU4ODQ=",
   avatar_url: "https://avatars.githubusercontent.com/u/3155884?v=4",
   gravatar_id: "",
   url: "https://api.github.com/users/MarkEdmondson1234",
   html_url: "https://github.com/MarkEdmondson1234",
   followers_url: "https://api.github.com/users/MarkEdmondson1234/followers",
   following_url: "https://api.github.com/users/MarkEdmondson1234/following{/other_user}",
   gists_url: "https://api.github.com/users/MarkEdmondson1234/gists{/gist_id}",
   starred_url: "https://api.github.com/users/MarkEdmondson1234/starred{/owner}{/repo}",
   subscriptions_url: "https://api.github.com/users/MarkEdmondson1234/subscriptions",
   organizations_url: "https://api.github.com/users/MarkEdmondson1234/orgs",
   repos_url: "https://api.github.com/users/MarkEdmondson1234/repos",
   events_url: "https://api.github.com/users/MarkEdmondson1234/events{/privacy}",
   received_events_url: "https://api.github.com/users/MarkEdmondson1234/received_events",
   type: "User",
   site_admin: false,
   name: "Mark",
   company: "@iihnordic ",
   blog: "https://code.markedmondson.me/",
   location: "Copenhagen",
   email: null,
   hireable: true,
   bio: "Data Engineer @iihnordic  \r\nGoogle Developer Expert, Google Analytics / Google Cloud\r\nTensorflow and R enthusiast",
   twitter_username: "HoloMarkeD",
   public_repos: 207,
   public_gists: 56,
   followers: 767,
   following: 116,
   created_at: "2012-12-30T23:42:23Z",
   updated_at: "2022-03-15T09:50:27Z"
 }